# Generated by Django 4.0.1 on 2022-02-04 02:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_email_alter_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_pict',
            field=models.ImageField(blank=True, upload_to='pp/', validators=[accounts.models.validate_image]),
        ),
    ]
