# Generated by Django 4.0.1 on 2022-02-08 00:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_profile_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pict',
            field=models.ImageField(blank=True, null=True, upload_to='pp/', validators=[accounts.models.validate_image]),
        ),
    ]
