# Generated by Django 4.0.1 on 2022-02-08 04:01

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_profile_pict'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(null=True, upload_to='banner/', validators=[accounts.models.validate_image])),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bannerbackground'),
        ),
    ]
